### ISSUE TITLE
Balance and TCV Incorrect in Testmode

### ISSUE THREAD

**Issue by dkr940** [taniman/profit-trailer#2036]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version: 2.1.5

 
Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

 
Market:
- [x] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ ] Windows (please specify version)
- [x] Ubuntu 16.04.4
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior

TCV should increase as sales (in profit) are made when the bot is running in test mode (taking into account any trades in PAIRS/DCA/PENDING). Instead after every profit sale the TCV (and balance) reduce or don't increase by as much as they should.

## Current Behavior

I started a bot today (2018-08-16) at 11:25 AM UTC and reset test data at 11:48 with PT version 2.1.5 using Old Faithful settings. The bot bought two coins - IOTA and ETC and subsequently sold both for a profit. Combined profit was 6122 sats according to the sales log. The bot started with 0.0874 BTC and now after the two sales the balance and TCV is showing as 0.08737342, which is less than the starting balance despite the fact that there is nothing in PAIRS, DCA, PENDING, or DUST, and only profits in the sales log.

I have noticed this behaviour for the last few 2.1 versions (not sure when it started though). I have noticed in the past that when I get a larger profit then the TCV does go up but not by the full amount of the profit, and smaller profits cause the TCV to reduce as is the case here.

I'm working on the basis that TCV should equal Start Balance + profits (or losses) in Sales Log - losses (or profits) in PAIRS/DCA/PENDING.

## Troubleshooting

Nothing I can do to fix this as far as I can tell.

## Steps to Reproduce

1. Reset PT data to start afresh
2. Buy and sell coins and check balance and TCV are as expected
3. 
4.

## Configuration

Standard OLD FAITHFUL (V4) default settings with start_balance = 0.0874 and max_pairs = 4 on BTC market.

## Log files/console output

 

2018-08-16 12:25:01 INFO Application - PT Version: 2.1.5
2018-08-16 12:25:01 INFO Application - Java Version: 1.8.0_171
2018-08-16 12:25:12 INFO Application$a - Server initialized with port: 8083
2018-08-16 12:25:24 INFO TelegramService - TEST MODE - Telegram message sent - PT BOT3 - ProfitTrailer Bot v2.1.5 started!
2018-08-16 12:25:24 INFO ProfitTrailerService - PAIRS Heartbeat
2018-08-16 12:25:24 INFO ProfitTrailerService - DCA Heartbeat
2018-08-16 12:25:28 INFO ProfitTrailerService - The bot will start trading at 16-08-2018 12:27
2018-08-16 12:25:31 INFO ProfitTrailerService - Cache Heartbeat
2018-08-16 12:35:26 INFO ProfitTrailerService - DCA Heartbeat
2018-08-16 12:35:28 INFO ProfitTrailerService - PAIRS Heartbeat
2018-08-16 12:35:33 INFO ProfitTrailerService - Cache Heartbeat
2018-08-16 12:45:27 INFO ProfitTrailerService - DCA Heartbeat
2018-08-16 12:45:31 INFO ProfitTrailerService - PAIRS Heartbeat
2018-08-16 12:45:34 INFO ProfitTrailerService - Cache Heartbeat
2018-08-16 12:48:58 INFO SettingsController - Resetting Test-Data
2018-08-16 12:48:58 INFO SettingsController - Test-Data resetted, the bot will start trading at 16-08-2018 12:53
.
.
2018-08-16 13:45:43 INFO ProfitTrailerService - DCA Heartbeat
2018-08-16 13:45:44 INFO ProfitTrailerService - Cache Heartbeat
2018-08-16 13:45:50 INFO ProfitTrailerService - PAIRS Heartbeat
2018-08-16 13:46:03 INFO ProfitTrailerService - Test mode: ["EMACROSS","EMAGAIN","LOWBB","RSI"] bought 1.17000000 ETCBTC price: 0.00214300, cost: 0.00250731
2018-08-16 13:46:03 INFO NormalStrategyRunner - Normal Pair - currency pair ETCBTC, MTP 4, TTP 1
2018-08-16 13:46:03 INFO TelegramService - TEST MODE - Telegram message sent - PT BOT3
Just bought: ETCBTC
Cost: 0.00250731
Rate: 0.00214300
2018-08-16 13:55:45 INFO ProfitTrailerService - DCA Heartbeat
2018-08-16 13:55:47 INFO ProfitTrailerService - Cache Heartbeat
2018-08-16 13:55:53 INFO ProfitTrailerService - PAIRS Heartbeat
2018-08-16 13:57:15 INFO ProfitTrailerService - Test mode: ["EMACROSS","EMAGAIN","LOWBB","RSI"] bought 35.00000000 IOTABTC price: 0.00007129, cost: 0.00249515
2018-08-16 13:57:15 INFO NormalStrategyRunner - Normal Pair - currency pair IOTABTC, MTP 4, TTP 2
2018-08-16 13:57:15 INFO TelegramService - TEST MODE - Telegram message sent - PT BOT3
Just bought: IOTABTC
Cost: 0.00249515
Rate: 0.00007129
2018-08-16 14:05:50 INFO ProfitTrailerService - DCA Heartbeat
2018-08-16 14:05:50 INFO ProfitTrailerService - Cache Heartbeat
2018-08-16 14:05:57 INFO ProfitTrailerService - PAIRS Heartbeat
.
.
2018-08-16 14:56:02 INFO ProfitTrailerService - Cache Heartbeat
2018-08-16 14:56:07 INFO ProfitTrailerService - DCA Heartbeat
2018-08-16 14:56:08 INFO ProfitTrailerService - PAIRS Heartbeat
2018-08-16 14:58:46 INFO ProfitTrailerService - Test mode: ["GAIN","RSI"] sold ETCBTC
2018-08-16 14:58:46 INFO TelegramService - TEST MODE - Telegram message sent - PT BOT3
Just sold: ETCBTC
Sell strat: GAIN,RSI
Cost: 0.00252300
Rate: 0.00217500
Profit: 1.29%
Profit BTC: 0.00003210
2018-08-16 14:58:46 INFO StrategyRunnerHelper - SELLLOG: {"buyProfit":0.0,"unfilledAmount":0.0,"market":"ETCBTC","currency":"ETC","base":"BTC","orderNumber":"","profit":1.291511083141017,"orderbookProfit":1.29,"averageCalculator":{"totalCost":0.002488368316000000,"totalAmount":1.16000000,"totalAmountWithSold":1.16883000,"avgPrice":0.0021451451,"avgCost":0.002507309947233000,"firstBoughtDate":{"date":{"year":2018,"month":8,"day":16},"time":{"hour":12,"minute":46,"second":3,"nano":253000000}},"lastBoughtDate":{"date":{"year":2018,"month":8,"day":16},"time":{"hour":12,"minute":46,"second":3,"nano":253000000}},"totalWeightedPrice":0.0025073100000000,"fee":0.1,"usedBuyHistory":[{"date":{"date":{"year":2018,"month":8,"day":16},"time":{"hour":12,"minute":46,"second":3,"nano":253000000}},"rate":0.00214300,"amount":1.17000000,"total":0.0025073100000000,"fee":0.001,"orderNumber":"981766","type":"buy"}],"usedSellHistory":[]},"currentPrice":0.002175,"buyStrategies":[],"sellStrategies":[{"type":"SELL","name":"GAIN","entryValue":1.0,"entryValueLimit":0.0,"triggerValue":0.0,"currentValue":1.57,"currentValuePercentage":0.0,"decimals":2,"positive":"true trailing..."},{"type":"SELL","name":"RSI","entryValue":65.0,"entryValueLimit":0.0,"triggerValue":0.0,"currentValue":97.40829099919027,"currentValuePercentage":0.0,"decimals":0,"positive":"true trailing..."}],"volume":6435.57443449,"percChange":0.17295,"boughtTimes":0,"originalTrailingData":{"lastSignal":false,"reboundCounter":0,"originalValue":1.0,"firstTrailTime":{"date":{"year":2018,"month":8,"day":16},"time":{"hour":13,"minute":56,"second":8,"nano":324000000}},"lastTrailTime":{"date":{"year":2018,"month":8,"day":16},"time":{"hour":13,"minute":59,"second":46,"nano":882000000}}}}
2018-08-16 15:06:04 INFO ProfitTrailerService - Cache Heartbeat
2018-08-16 15:06:09 INFO ProfitTrailerService - DCA Heartbeat
2018-08-16 15:06:09 INFO ProfitTrailerService - PAIRS Heartbeat
2018-08-16 15:08:13 INFO ProfitTrailerService - Test mode: ["GAIN","RSI"] sold IOTABTC
2018-08-16 15:08:13 INFO TelegramService - TEST MODE - Telegram message sent - PT BOT3
Just sold: IOTABTC
Sell strat: GAIN,RSI
Cost: 0.00245786
Rate: 0.00007229
Profit: 1.20%
Profit BTC: 0.00002916
2018-08-16 15:08:13 INFO StrategyRunnerHelper - SELLLOG: {"buyProfit":0.0,"unfilledAmou
nt":0.0,"market":"IOTABTC","currency":"IOTA","base":"BTC","orderNumber":"","profit":1.203251121076232,"orderbookProfit":1.2,"averageCalculator":{"totalCost":0.00242628627400000000,"totalAmount":34.00000000,"totalAmountWithSold":34.96500000,"avgPrice":0.000071361361,"avgCost":0.00249514998736500000,"firstBoughtDate":{"date":{"year":2018,"month":8,"day":16},"time":{"hour":12,"minute":57,"second":15,"nano":894000000}},"lastBoughtDate":{"date":{"year":2018,"month":8,"day":16},"time":{"hour":12,"minute":57,"second":15,"nano":894000000}},"totalWeightedPrice":0.0024951500000000,"fee":0.1,"usedBuyHistory":[{"date":{"date":{"year":2018,"month":8,"day":16},"time":{"hour":12,"minute":57,"second":15,"nano":894000000}},"rate":0.00007129,"amount":35.00000000,"total":0.0024951500000000,"fee":0.001,"orderNumber":"795556","type":"buy"}],"usedSellHistory":[]},"currentPrice":7.229E-5,"buyStrategies":[],"sellStrategies":[{"type":"SELL","name":"GAIN","entryValue":1.0,"entryValueLimit":0.0,"triggerValue":0.0,"currentValue":1.5395739910314066,"currentValuePercentage":0.0,"decimals":2,"positive":"true trailing..."},{"type":"SELL","name":"RSI","entryValue":65.0,"entryValueLimit":0.0,"triggerValue":0.0,"currentValue":48.37526678487308,"currentValuePercentage":0.0,"decimals":0,"positive":"true trailing..."}],"volume":767.91276251,"percChange":-0.03145,"boughtTimes":0,"originalTrailingData":{"lastSignal":false,"reboundCounter":0,"originalValue":1.0,"firstTrailTime":{"date":{"year":2018,"month":8,"day":16},"time":{"hour":13,"minute":42,"second":56,"nano":891000000}},"lastTrailTime":{"date":{"year":2018,"month":8,"day":16},"time":{"hour":14,"minute":9,"second":13,"nano":695000000}}}}
2018-08-16 15:16:07 INFO ProfitTrailerService - Cache Heartbeat
2018-08-16 15:16:12 INFO ProfitTrailerService - DCA Heartbeat
2018-08-16 15:16:12 INFO ProfitTrailerService - PAIRS Heartbeat

**Comment by taniman** [comment]
Please upload your log file as a file. And your profittrailerdata.json

**Comment by dkr40** [comment]
Sorry about that, here are the files as requested.

[ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/2294347/ProfitTrailer.log)
[ProfitTrailerData.json.zip](https://github.com/taniman/profit-trailer/files/2294352/ProfitTrailerData.json.zip)

**Comment by dkr40** [comment]
Screenshot attached for the bot that has since bought two more coins (both in profit). TCV should be showing a value above start balance (0.0874), but is showing a value less than that.
![screen shot 2018-08-16 at 19 51 55](https://user-images.githubusercontent.com/42444709/44228891-577c6c00-a18e-11e8-8375-4983ce4645d7.png)

I also have another test bot started around the same time using Spanish Cross settings that has same problem.

![screen shot 2018-08-16 at 19 57 22](https://user-images.githubusercontent.com/42444709/44228994-a2967f00-a18e-11e8-8626-4a1333fae516.png)

**Comment by m4xson** [comment]
I had this as well possibly. Every time I ran a test bot the TCV would drop all the time even if the bot made profitable sells. I had been putting this down to the bot having some bags but I was running a stoploss so bags were small.

**Comment by taniman** [comment]
I have looked and made many buys and sells. But could not get this to replicate to be honest. 

I have however made some changed in 2.1.6 to make test mode behave a bit more consistent and if this happens again we could then try to run by all buys and sells and see what went wrong. 

Possible fix in 2.1.6

**Comment by dkr40** [comment]
Ok, thanks. I will try with a fresh bot once 2.1.6 is released. 

In the meantime I show a screenshot for another bot running Old Faithful settings that I started afresh after raising this issue. As you can see profits shown in the Sales log are 0.00068130 BTC, DCA is currently -0.00061331, nothing in Pairs or Pending. Therefore TCV showing be showing a small profit of 0.00006799 (maybe slightly less if exchange fees aren't included in DCA calculations). However TCV is down -0.00088755 BTC, which can't be explained by fees alone.

![screen shot 2018-08-22 at 14 19 02](https://user-images.githubusercontent.com/42444709/44466165-858eff80-a617-11e8-87f6-23d3b4fc0d47.png)

**Comment by TheBigShort111** [comment]
For what its worth, I'm having this same issue under the exact same circumstances... Have a test bot running, trying various changes, and have reset the bot several times to compare the changes... PT is not keeping an accurate Balance or TCV.

Started with a $900.00 test balance... As you can see, two trades complete, with a 0.88693716 profit, yet the balance only shows a .158 gain. As with the original poster, this figure was off at the first trade, then further off at the second... I have been noticing this behavior for a while now, but only today has it become frustrating enough that I did a search to see if anyone else is/was having the same issue.

I'm running the latest release in testmode, USDT market.

**Comment by m4xson** [comment]
This is happening with my 2.1.12 test bot.

**Comment by taniman** [comment]
This issue has been closed. So create a new one and provide proper details so we can investigate. Thank you

**Comment by taniman** [comment]
I've decided to reopen this one.

**Comment by TheBigShort111** [comment]
You mentioned you decided to reopen this, but it is still closed.

**Comment by taniman** [comment]
Fixed in 2.1.22

**Comment by TheBigShort111** [comment]
This is great news!! - Thanks for all the work you do!

**Comment by jokaorgua** [comment]
using version 2.1.23 - TCV is still wrong

DCA
Current Value | 0.68198176($3,834.24)
Difference | (-1.59 %) -0.01101680($-61.94)
Total Cost | 0.69299856($3,896.18)

Sales
Bought Cost | 0.60994766($3,428.71)
Difference | (0.68 %) 0.00416098($23.39)
Sold Value


Pairs
Current Value	0.00601546 ($33.82)
Difference	(0.16 %) 0.00000970 ($0.05)
Bought Cost	0.00600576 ($33.76)

TCV
0.97041573 BTC
Total Current Value
USD Estimated Value  5,455.66
TCV with Dust 0.97041573 BTC

**Comment by taniman** [comment]
@jokaorgua  Please create a new bug report if you feel this is not fixed. 
And provide proper data. As required by any new issue. 

Also be aware that the problem was fixed for new sales. So if your TCV was already wrong due to the previous bug it will not be fixed no matter what.
