### ISSUE TITLE
PT lost bought price combined pending orders

### ISSUE THREAD

**Issue by mightysoul** [taniman/profit-trailer#2047]
NO NEW FEATURES! Use [PT Enahancements](https://github.com/taniman/profit-trailer-enhancements) for Feature Requests.

## ProfitTrailer info
Version: 2.1.5 TEST MODE

 
Exchange:
- [ ] Bittrex
- [x] Binance
- [ ] Poloniex

 
Market:
- [x] BTC
- [ ] ETH
- [ ] USDT
- [ ] BNB
- [ ] XMR

 
Operating System:
- [ ] Windows (please specify version)
- [x] Ubuntu (please specify version)
- [ ] Other linux distro (please specify)
- [ ] Mac OS

## Expected Behavior

PT shouldn't lost average bought price when DEFAULT_combine_pending_orders = false

## Current Behavior

PT lost average bought price. 

## Steps to Reproduce

1. I've used default spanish cross strategy.
2. I've only added DEFAULT_combine_pending_orders = false
[ProfitTrailer.txt](https://github.com/taniman/profit-trailer/files/2315044/ProfitTrailer.txt)

3.
4.

**Comment by taniman** [comment]
PT does not lose bought price just because you add this option. 

Please use 2.1.6 which we released as there are plenty of fixes to help with lost bought prices while working with pending orders.

But these will only take effect for pending orders that are created after the update. So for now you will have to set the bought prices. As the bot was never optimized to work with so many pending orders until now.

**Comment by mightysoul** [comment]
Just Upgraded to 2.1.7. Problem persists :(. ADA pending order created after the update. 

![image](https://user-images.githubusercontent.com/37293938/44565986-ac624880-a773-11e8-9d14-b9bdf5c6e6dd.png)

[ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/2317082/ProfitTrailer.log)

**Comment by taniman** [comment]
Get me file named -838753859 in unaccounted folder too

**Comment by mightysoul** [comment]
Hi,

I'm not sure how to reproduce this problem but same problem didn't occur for other pairs like XLM. 

Bot bought ada in 2.1.6
Send to pending in 2.1.6

ADA was on pending then price probably rised and combined profit reached to 0.25 then I saw ADA on pairs log with zero price. 

I've attaced to requested data.I've also attached my Pairs settings


[ProfitTrailerData.zip](https://github.com/taniman/profit-trailer/files/2318216/ProfitTrailerData.zip)

**Comment by taniman** [comment]
Problem fixed in 2.1.8
