### ISSUE TITLE
[BUG] Out of memory error on v1.2.6.12

### ISSUE THREAD

**Issue by bruce133** [taniman/profit-trailer#847]
ProfitTrailer with PT Feeder on Raspberry Pi 3 ran for days without error on older versions. Now after half a day it bugs out with this message:

```
ERROR TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.OutOfMemoryError: Java heap space
```

While the device only has 1 GB of RAM, over a quarter of it should still be available:

```
$ free -m
              total        used        free      shared  buff/cache   available
Mem:            927         556          32          43         337         276
Swap:            99           6          93
```

I'm no expert, but I figure that there's enough physical memory, and Java probably has it's own default memory limit (percentage based perhaps?), which you're hitting due to memory leaks.

Edit: On a positive note, it seems this downtime actually was a stroke of luck. Right when PT bugged out, VENETH started rising. PT would likely have sold it off after trailing one or two of the hills, but I didn't get it running again till just a moment ago. It finally sold at almost 15% profit, netting me about $180. 😄 

![image](https://user-images.githubusercontent.com/2420663/35456337-5fae171e-02d5-11e8-8699-08fede320094.png)

**Comment by cristianserban** [comment]
how many pairs are you trading? 
what version of java are you using?

**Comment by ba32107** [comment]
This happened to me too. I am also running on Raspberry Pi 3 (but no Feeder, only PT). I was also on 1.2.6.12. I reverted to 1.2.6.10 since. I am trading 10 pairs max. At the time the issue occurred, I was in SOM and 8 pairs were in DCA. I'm using Java 1.8.0_161.

Stack trace:

.... many same lines before this....
2018-01-25 02:04:59 ERROR BinanceWebSocketAdapter24Ticker - Error in websocket message ERROR: -1003, Too many requests; current limit is 1200 requests per minute. Please use the websocket for live updates to avoid polling the API.
2018-01-25 02:05:00 ERROR BinanceWebSocketAdapter24Ticker - Error in websocket message ERROR: -1003, Too many requests; current limit is 1200 requests per minute. Please use the websocket for live updates to avoid polling the API.
2018-01-25 02:05:00 ERROR BinanceWebSocketAdapter24Ticker - Error in websocket message ERROR: -1003, Too many requests; current limit is 1200 requests per minute. Please use the websocket for live updates to avoid polling the API.
2018-01-25 02:05:00 INFO GenericStrategyRunner - Cooling down for 1 minute
2018-01-25 02:05:05 ERROR BinanceWebSocketAdapter24Ticker - onWebSocketError: RSV2 not allowed to be set
2018-01-25 02:05:05 ERROR BinanceWebSocketAdapter24Ticker - onWebSocketError: RSV2 not allowed to be set
2018-01-25 02:05:08 ERROR BinanceWebSocketAdapter24Ticker - Error in websocket message com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 47843 path $
2018-01-25 02:05:11 ERROR BinanceWebSocketAdapter24Ticker - onWebSocketError: Unknown opcode: 11
2018-01-25 02:05:11 ERROR BinanceWebSocketAdapter24Ticker - onWebSocketError: Unknown opcode: 5
2018-01-25 02:05:16 ERROR BinanceWebSocketAdapter24Ticker - Error in websocket message Expected a com.google.gson.JsonArray but was com.google.gson.JsonObject
2018-01-25 02:05:16 ERROR BinanceWebSocketAdapter24Ticker - onWebSocketError: RSV2 not allowed to be set
2018-01-25 02:05:27 ERROR BinanceWebSocketAdapter24Ticker - onWebSocketError: Unknown opcode: 12
2018-01-25 02:05:30 ERROR BinanceWebSocketAdapter24Ticker - onWebSocketError: CONTINUATION frame without prior !FIN
2018-01-25 02:06:00 INFO GenericStrategyRunner - We got temp banned. Waiting 5 minutes
2018-01-25 02:07:29 ERROR BinanceWebSocketAdapter24Ticker - onWebSocketError: Unknown opcode: 4
2018-01-25 02:08:17 ERROR BinanceWebSocketAdapter24Ticker - onWebSocketError: RSV2 not allowed to be set
2018-01-25 02:08:42 ERROR BinanceWebSocketAdapter24Ticker - onWebSocketError: Unknown opcode: 11
2018-01-25 02:09:06 ERROR BinanceWebSocketAdapter24Ticker - onWebSocketError: RSV2 not allowed to be set
2018-01-25 02:11:10 INFO ProfitTrailerService - Normal Heartbeat
2018-01-25 02:11:26 INFO ProfitTrailerService - DCA Heartbeat
2018-01-25 02:13:39 ERROR BinanceWebSocketAdapter24Ticker - onWebSocketError: java.lang.OutOfMemoryError: Metaspace
2018-01-25 02:13:42 ERROR BinanceWebSocketAdapter24Ticker - onWebSocketError: java.lang.OutOfMemoryError: Metaspace
2018-01-25 02:13:53 ERROR BinanceWebSocketAdapter24Ticker - onWebSocketError: java.lang.OutOfMemoryError: Metaspace
2018-01-25 02:13:58 ERROR BinanceWebSocketAdapter24Ticker - onWebSocketError: java.lang.OutOfMemoryError: Metaspace
2018-01-25 02:13:55 ERROR BinanceWebSocketAdapter24Ticker - onWebSocketError: java.lang.OutOfMemoryError: Metaspace
2018-01-25 02:14:04 ERROR ProfitTrailerService - Handled exception Metaspace
2018-01-25 02:14:12 ERROR BinanceWebSocketAdapter24Ticker - onWebSocketError: java.lang.OutOfMemoryError: Metaspace
2018-01-25 02:14:07 ERROR BinanceWebSocketAdapter24Ticker - onWebSocketError: java.lang.OutOfMemoryError: Metaspace
.... many same lines after this

**Comment by stambi** [comment]
Same Problem here. Also ProfitTrailer running on a Pi 3. 8 Pairs on Binance, does not happen with the same configuration / hardware trading on Bittrex. Back to 1.2.6.10 for now.

**Comment by orty87** [comment]
Same here. Tried do increese the heap space but it didn't help.

**Comment by TerrenceHenry** [comment]
Same here, on my Pi 3. One pair, One DCA!
java.lang.OutOfmemoryError: Jabva heap space

**Comment by Gitulu** [comment]
Hello guys,

Same thing for me here with 1.2.6.12 and increased memory settings with the following start parameters for both bots on Binance.
`java -jar ProfitTrailer.jar -XX:+UseConcMarkSweepGC -Xmx1024m -Xms1024m`

Furthermore I got additional a Websocket error: "ERROR BinanceWebSocketAdapterKline - onWebSocketError: Timeout on Read"

[ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/1670003/ProfitTrailer.log)
![trailer](https://user-images.githubusercontent.com/35115314/35471305-f0f7ba58-0358-11e8-8c13-8b9fa7973f03.png)
![taskmanager](https://user-images.githubusercontent.com/35115314/35471306-f110a2b6-0358-11e8-89a1-c5052b7e6ae3.png)

The bot does not work correctly and it does not run a complete day without errors.
Please check this I will help with more information if you need.

Thanks

**Comment by jvanthof** [comment]
Same here on RPi 3, v1.2.6.12 with 10 pairs max (at time of crash only 2 pairs in pairs log and 4 in dca). Starting with pm2 script (I think its the 512m setting) and restarted just "as is". Will see how long it will run for now, before reverting to 1.2.6.10...

**Comment by furlat** [comment]
confirmed memory leak on t2.micro aws instance, same version. Doubled the ram..

**Comment by masterpropper** [comment]
same here, running on debian vps

**Comment by Gitulu** [comment]
This happened again this night. To make sure the bots will run run the whole night I have restarted bot bots.

This morning the surprise is both save files: "ProfitTrailerData.json" and "ProfitTrailerData.json.backup" - result: "NUL" are corrupted for each bot.

Attached you will find all files you need to check.
I have downgraded to 1.2.6.11 until the fix.

[ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/1670961/ProfitTrailer.log)

Thanks

**Comment by bruce133** [comment]
Sorry for the delayed response, I was in London the whole yesterday. 

> how many pairs are you trading?
what version of java are you using?

I was trading with either 5 or 8 pairs. 

My Java version:

```
$ java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) Client VM (build 25.151-b12, mixed mode)
```

**Comment by dA1k0** [comment]
same here, win 10

**Comment by cristianserban** [comment]
We are testing a fix for this issue.. as soon as it gets the ok we will release it
Thanks for understanding..

**Comment by bruce133** [comment]
Anyone tried to see if it's fixed in v1.2.6.14?

**Comment by ba32107** [comment]
Been running it for a day, haven't seen the error yet.

**Comment by djkemp** [comment]
I'm running .14 and have still experienced the issue for clarification.

**Comment by Gitulu** [comment]
With the version 1.2.6.14 I do not have this memory issue anymore. I have started both bots with:
`java -jar ProfitTrailer.jar -XX:+UseConcMarkSweepGC -Xmx1024m -Xms1024m`

Runs very well since the release. I have noticed in the log other small errors but no crashing my bot which is good.

**Comment by dA1k0** [comment]
Still have the error. It takes longer to take effect but its the same error. Win10

**Comment by orty87** [comment]
I also still have the issue with 1.2.6.14 ony rpi 3.

**Comment by Gitulu** [comment]
The 1.2.6.14 runs good but not stable on Win 10. Tonight I have received the error: "ERROR TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task." The webinterface is ready but nothing changed after a look in the log files I found this. I restarted the bot an wooow it sold one pair.

Error:

`ERROR TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_161]
	at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_161]
	at nl.komtek.pt.services.ProfitTrailerService.e(ProfitTrailerService.java:1153) ~[classes!/:1.2.6.14]
	at nl.komtek.pt.services.ProfitTrailerService$$FastClassBySpringCGLIB$$75b7acd9.invoke(<generated>) ~[classes!/:1.2.6.14]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:652) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at nl.komtek.pt.services.ProfitTrailerService$$EnhancerBySpringCGLIB$$48f48e27.e(<generated>) ~[classes!/:1.2.6.14]
	at nl.komtek.pt.strategyrunner.DCAStrategyRunner.checkDCAStrategy(DCAStrategyRunner.java:53) ~[classes!/:1.2.6.14]
	at sun.reflect.GeneratedMethodAccessor41.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_161]`

More Attached.

Thank you
[ProfitTrailer.log](https://github.com/taniman/profit-trailer/files/1692771/ProfitTrailer.log)

**Comment by bruce133** [comment]
New day, new release. I wonder, is v1.2.6.15 the stable version we've been waiting for? Anyone care to test?

**Comment by djkemp** [comment]
Just updated so will see...

**Comment by bruce133** [comment]
I updated to v1.2.6.16 about an hour ago, and so far it seems to be holding steady.
